// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jouidoxxiflwykkifnew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvdWlkb3h4aWZsd3lra2lmbmV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODcwOTMsImV4cCI6MjA2MTE2MzA5M30.rPCqkJNnN6mizVDV4B_4Kk36JXsQ-IXCJVaKtB3H_Yk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);